#!/bin/bash
#$ -j y
#$ -cwd
#$ -S /bin/bash
#$ -pe mpi 18
#$ -q low.q
#$ -m a

hostname
# prefix will be the samples name
sample_name=`basename ${bam}| awk 'BEGIN{FS="."}{print $1}'`

# replace this with your own path to mosdepth
/home/dlin/miniconda3/envs/mose/bin/mosdepth --by ${bed} -T 10,20,50,100,500,1000 -x ${sample_name} ${bam}
/home/dlin/miniconda3/envs/mose/bin/bedtools intersect -a ${sample_name}.per-base.bed.gz -b ${bed} > ${sample_name}.bedtools.out
# Use -n to skip per-base output, use it when doing large scale scan
# /home/dlin/miniconda3/envs/mose/bin/bedtools intersect -a ${sample_name}.per-base.bed.gz -n -b ${bed} > ${sample_name}.bedtools.out
/home/dlin/miniconda3/envs/mose/bin/python3.7 per_base_convert.py ${sample_name}.bedtools.out